version: '3.3'

services:
  web:
    image: docker.pkg.github.com/treker-mk/website/web:latest
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.http.routers.sledilnik.rule: "Host(`test.treker.mk`) || Host(`www.treker.mk`) || Host(`treker.mk`) || Host(`covid-19.treker.mk`) || Host(`www.covid-19.treker.mk`) "
      traefik.http.routers.sledilnik.tls: true

networks:
  traefik:
    external:
      name: lb_traefik
